### ISSUE TITLE
看了你关于Cahe的这篇文章，Swift的Cache确实比较少。

### ISSUE THREAD

**Issue by arden** [maquannene/Track#5]
最近我也一直比较关注Swift版本的Cache，目前用的是AwesomeCache，但功能确实有限。不过前段时间发现一个功能比较完善的Cache框架，你也可以对比下性能测试。

https://github.com/hyperoslo/Cache

**Comment by arden** [comment]
其实我现在最关心的是对缓存的对象类型有什么要求不？像AwesomeCache就不能存储自定义的数据模型。

**Comment by maquannene** [comment]
Cache DiskCache 的对象必须支持 NSCoding 协议，因为要基于文件，必须支持解编码。
MemoryCache 没要求，AnyObject 就行。

你下面发的那个 Cache，同步读写我看了一下，也是异步读写加信号量锁变同步，属于我写的第一种线程调度模型。它采用的是串行队列，不会产生死锁问题，但是性能还是会低。

Mem 底层用的 NSCache，也会出现我分析的那种问题。

**Comment by arden** [comment]
其实我觉得 https://github.com/hyperoslo/Cache 比较好的地方是，对缓存的对象类型比较好，可以自定义。我目前用的是AwesomeCache,要求缓存的对象也是要实现NSCoding协议，但是这种方式感觉不是很理想，像我目前项目里有用到ObjectMapper, Realm等json、数据库操作的框架，不想再为了缓存再实现一套基于NSCoding的东西，并且实现NSCoding后，模型和realm就会有一些冲突。

**Comment by maquannene** [comment]
恩，看到了，他有自己的一个编码协议 Cachable，也需要模型实现。
后期会考察一下，我也觉得非要实现 Coding 协议有点局限，可能的话会想办法改善。

**Comment by arden** [comment]
嗯，我最近也非常关心缓存这块，需要一个合适的缓存库，希望能够用得上你这个。另外底层存储基于Realm实现一套缓存技术上怎么样？

**Comment by maquannene** [comment]
Disk 底层近期不考虑 Realm，这个东西定位只是支持一些逻辑简单的数据存储，没有必要再让使用者被动引入 Realm 这个庞大的库。

**Comment by StoneStoneStoneWang** [comment]
## Third
    s.subspec 'WLThird' do |third|
    third.dependency 'Cache'
    end
您好 我在用Cache的时候 pod lib lint通不过验证
